### ISSUE TITLE
Videoda gecikme

### ISSUE THREAD

**Issue by AbdullahOztuurkk** [emincanozcan/armagan-amcalardan-kisa-cevaplar#2]
Öncelikle oluşturduğunuz projeyi oldukça beğendim, tebrik ederim. Sorular arasında dolaşırken "Junior front-end olarak iş başvuruları yaptım ama dönüş olmadı. Pandeminin buna etkisi nedir?" sorusunun cevabının 10 saniye sonra başladığını farkettim. Küçük bir sorun olsa da size belirtmek istedim. 10:38'de başlaması gerekirken 10:28'de video başlıyor.

**Comment by emincanozcan** [comment]
Bahsettiğin videoyu kontrol ettim. Sorun yazılımdan kaynaklanmamış, Youtube'da video açıklamasına yanlış zaman yazılmış. Aynı videonun açıklamasında başka bir hataya daha denk geldim. Uygulamanin veri setinde manuel düzeltme yapabilirim ancak hem sonraki otomatik veri oluşturma işlemlerinde sıkıntı olmaması açısından hem de direkt Youtube'dan videoyu izleyen kişilerin doğru yönlendirilebilmesi açısından @dashersw 'den video açıklamasını düzenlemesini rica etmek daha doğru olur. 

**Kolay ulaşılabilmesi adına toparlamak gerekirse:**

Video linki: [https://www.youtube.com/watch?v=2D0jA61zuWU](https://www.youtube.com/watch?v=2D0jA61zuWU)

"Junior front-end olarak iş başvuruları yaptım ama dönüş olmadı. Pandeminin buna etkisi nedir?" sorusu 10:28 olarak kaydedilmiş, 10:38 olarak değiştirilmeli.

"Bir Startup için React Native ile scooter sharing uygulaması geliştirdim. React Native gelecekte nasıl bir sorun yaratabilir?" Zaman olarak (01.01) yazılmış ancak bu format Youtube için de geçerli değil, uygulama da parse etmiyor. Dolayısıyla  (01:01) olarak düzenlenmeli.

Geri bildirimin için teşekkürler.
